In [1]:
# ambiente anaconda
import sys
print(sys.executable)

/home/fabiene/anaconda3/envs/Udemy/bin/python


In [2]:
# versão do python
print(sys.version)

3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]


# 35.4) Matrizes

In [3]:
import numpy as np

In [4]:
# para funções estatísticas, inteligência artificial, matrizes

In [5]:
# fazer matrizes
matriz = np.array([[2, 3, 1],
                   [4, 5, 7]])

In [6]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [8]:
matriz.shape  # a matriz tem 2 linhas e 3 colunas

(2, 3)

In [9]:
# primeira linha
matriz[0]

array([2, 3, 1])

In [10]:
# segunda linha
matriz[1]

array([4, 5, 7])

In [11]:
matriz[0][0] # linha 0 e coluna 0

np.int64(2)

In [12]:
matriz[0][1] # linha 0 e coluna 1

np.int64(3)

In [13]:
matriz[0][2] # linha 0 e coluna 2

np.int64(1)

In [14]:
matriz[1][2] # linha 1 e coluna 2

np.int64(7)

In [15]:
matriz.shape

(2, 3)

In [16]:
# rodar as matrizes

In [26]:
for i in range(matriz.shape[0]): # percorrer as linhas
  print(f'i {i}')
  print(f'matriz: {matriz[i]}')
  for j in range(matriz.shape[1]): # percorrer as colunas
    #print(f'(i {i} e j {j})')
    print(f'matriz ({i},{j}): {matriz[i][j]}')


i 0
matriz: [2 3 1]
matriz (0,0): 2
matriz (0,1): 3
matriz (0,2): 1
i 1
matriz: [4 5 7]
matriz (1,0): 4
matriz (1,1): 5
matriz (1,2): 7
