# Reconhecimento Facial 


anaconda ambiente 

conda env list

conda activate pycaret-env


trocamos para o ambiente

### no linux: 

só funciona o programa no python  3.10 e na versão opencv 4.5

conda create -n face-env python=3.10 -y

conda activate face-env

pip install opencv-contrib-python==4.5.5.64

pip install opencv-contrib-python==4.5.5.64

conda install jupyter -y

pip install notebook




In [1]:
#  conda env list
# # conda environments:
# #
# base                  *  /home/fabiene/anaconda3
# Maq2                     /home/fabiene/anaconda3/envs/Maq2
# RBA_est                  /home/fabiene/anaconda3/envs/RBA_est
# Robyn                    /home/fabiene/anaconda3/envs/Robyn
# Udemy                    /home/fabiene/anaconda3/envs/Udemy
# YouTube                  /home/fabiene/anaconda3/envs/YouTube
# face-env                 /home/fabiene/anaconda3/envs/face-env
# orange3                  /home/fabiene/anaconda3/envs/orange3
# pycaret-env              /home/fabiene/anaconda3/envs/pycaret-env



método convulacional para detectar faces. OpenCV

In [2]:
#!pip install pillow


In [3]:
# biblioteca para leitura de imagem
from PIL import Image
import numpy as np

In [4]:
# acessar os arquivos dentro do zip
import zipfile
path = 'yalefaces.zip'
# dezipando o arquivo, ou descompactar.
zip_object = zipfile.ZipFile(file=path, mode='r') # mode r para read, ou leitura
zip_object.extractall('./')
zip_object.close()  # para liberarmos a memória

In [5]:
zip_object  # imagem de treino da universidade de yale.

<zipfile.ZipFile [closed]>

In [6]:
# pastas de teste e de treinamento
# fotos de rosto com várias expressões
# ber o padrão, para depois selecionar ou testar.
# nome das pessoas são os id ou número na legenda das fotos.

In [7]:
import os
os.listdir('yalefaces/train/')

['subject13.centerlight.gif',
 'subject02.happy.gif',
 'subject15.surprised.gif',
 'subject12.centerlight.gif',
 'subject13.noglasses.gif',
 'subject10.surprised.gif',
 'subject15.sleepy.gif',
 'subject03.wink.gif',
 'subject12.glasses.gif',
 'subject07.normal.gif',
 'subject06.noglasses.gif',
 'subject09.leftlight.gif',
 'subject01.leftlight.gif',
 'subject14.surprised.gif',
 'subject15.glasses.gif',
 'subject06.rightlight.gif',
 'subject08.wink.gif',
 'subject07.wink.gif',
 'subject08.leftlight.gif',
 'subject09.surprised.gif',
 'subject03.surprised.gif',
 'subject02.rightlight.gif',
 'subject02.glasses.gif',
 'subject15.noglasses.gif',
 'subject05.centerlight.gif',
 'subject12.wink.gif',
 'subject11.sleepy.gif',
 'subject02.sleepy.gif',
 'subject03.normal.gif',
 'subject05.wink.gif',
 'subject03.sleepy.gif',
 'subject13.happy.gif',
 'subject06.centerlight.gif',
 'subject04.centerlight.gif',
 'subject10.glasses.gif',
 'subject06.sleepy.gif',
 'subject11.centerlight.gif',
 'subject07.

In [8]:
# colocar a foto em numpy retorna uma matriz, lembrando que a foto está em pixel que vai de 0 a 255.

Imagem com a mesma dimensão 320x243, em RGB, todas com o mesmo tamanho.

320*243=77760 pixels em cada uma das imagens.

a foto está na cor cinza o que acelerará o processo de treinamento.

Se fosse RGB haveria 3 canais de cores, 3 etapas para treinar.

In [9]:
os.path.join('yalefaces/train/', 'subject10.wink.gif') # nome completo do arquivo e sua pasta

'yalefaces/train/subject10.wink.gif'

In [10]:
int(os.path.split(os.path.join('yalefaces/train/', 'subject10.wink.gif'))[1].split('.')[0].replace('subject', ''))

10

In [11]:
os.path.split(os.path.join('yalefaces/train/', 'subject10.wink.gif'))[1].split('.')[0]

'subject10'

In [12]:
os.path.split(os.path.join('yalefaces/train/', 'subject10.wink.gif'))[1]

'subject10.wink.gif'

In [13]:
def dados_imagem():
  # arquivo em .gig
  caminhos = [os.path.join('yalefaces/train/', f) for f in os.listdir('yalefaces/train/')] # ver a pasta de treinamento, listar todos os diretórios
  faces = []
  ids = []
  for caminho in caminhos:
    # Este if é caso usar o jupyter notebook do colab  
    if caminho == 'yalefaces/train/.ipynb_checkpoints':
      continue
    imagem = Image.open(caminho).convert('L') # conversão para a escala cinza.
    imagem_np = np.array(imagem, 'uint8') # a imagem será convertido em matriz np e será só número inteiro.
    id = int(os.path.split(caminho)[1].split('.')[0].replace('subject', ''))
    ids.append(id)
    faces.append(imagem_np) 
  return np.array(ids), faces

In [14]:
ids, faces = dados_imagem()

In [15]:
print(ids) # vetor ids

[13  2 15 12 13 10 15  3 12  7  6  9  1 14 15  6  8  7  8  9  3  2  2 15
  5 12 11  2  3  5  3 13  6  4 10  6 11  7  9  6  9  9 14 13  4  2 14  3
  7  9  8 11  5 11  7  1  5  1  3  4 15  4  3  6 13  5  9 13  3 14  5  4
  2  1 15  5 10 13 10  8 14  9 11 12  6  2 12  3  7 15 14 13  6  5 13 15
  1 14 12 12  4  7  4  4 11  2  2 14 11 14 10 10  9 15 10  8  7 10  8 11
  8  1  6  4  1  8  8  7  5 12 12  1 10 11  1]


In [16]:
set(ids) # há 15 pessoas, com suas faces nas fotos.

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}

In [17]:
print(faces)

[array([[130, 130, 130, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 237, 231, 237],
       [255, 255, 255, ..., 241, 236, 244],
       [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8), array([[109, 111, 124, ..., 255, 255, 243],
       [235, 239, 255, ..., 255, 253, 244],
       [253, 255, 255, ..., 253, 251, 243],
       ...,
       [255, 255, 255, ..., 187, 183, 183],
       [255, 255, 255, ..., 183, 180, 179],
       [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8), array([[130, 130, 130, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 235, 238, 255],
       [255, 255, 255, ..., 234, 243, 255],
       [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8), array([[130, 130, 130, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 

In [18]:
print(faces[0]) #id 13, matriz que representa a imagem

[[130 130 130 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 237 231 237]
 [255 255 255 ... 241 236 244]
 [ 68  68  68 ...  68  68  68]]


# treinamento => Local Binary Pattern Histograms

In [19]:
#!pip install opencv-contrib-python==4.5.5.64



Estamos no ambiente pycaret-env com Python 3.11, e o LBPH não funciona em Python 3.11.

In [20]:
#!pip install numpy==1.23.5 --force-reinstall


In [21]:
import cv2 # OpenCV

Versão OpenCV	cv2.face disponível?	

Observação
4.5.5.64	✅ Sim	Recomendado

4.6.x	✅ Algumas builds	Pode falhar

4.7+	❌ Removido	Seu caso

In [22]:
import cv2
print(cv2.__version__)

recognizer = cv2.face.LBPHFaceRecognizer_create()
print("OK! LBPH funcionando.")


4.5.5
OK! LBPH funcionando.


In [24]:

lbph = cv2.face.LBPHFaceRecognizer_create() # criação padrão
lbph.train(faces, ids)
lbph.write('classificador_face_LBPH_aula.yml')  # arquivo em yml criado como base de treinamento das faces, em matriz.