# 7.9) Regressão Logística - Base Risco Crédito

In [4]:
import pickle
# read =rb 

with open('../4-Bayesiana/risco_credito.pkl', 'rb') as f:
          X_risco_credito, y_risco_credito = pickle.load(f)

dados:

[historia, divida, garantias, renda | risco]

[ruim, alta, nenhuma, 0_15 | alto]



In [5]:
X_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [7]:
y_risco_credito # -> classes : utilizar apenas as classes alto e baixo, para associar com as aulas teoricas. 

# 2, 7, 11  apagar os moderados

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [9]:
import numpy as np

X_risco_credito = np.delete(X_risco_credito, [2, 7, 11], axis = 0) # axis é o eixo, 0 apagar a linha, axis =1 apagar coluna
y_risco_credito = np.delete(y_risco_credito, [2, 7, 11], axis = 0)


In [10]:

# dados reduzidos

X_risco_credito



array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [11]:
y_risco_credito

array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'alto', 'baixo', 'baixo',
       'alto', 'baixo', 'alto'], dtype=object)

### Importar a biblioteca 

In [12]:
from sklearn.linear_model import LogisticRegression

#### fazer de fato o terinamento algoritmo e achar os parâmetros da equação da reta b0, b1, b2,b3,b4.. além de achar o valor p da Função sigmoide

In [14]:
logistic_risco_credito = LogisticRegression(random_state = 1) # pode ser qualquer valor, random_state 
# e cada vez que executarmos esse algoritmo teremos sempre o mesmo valor, tudo com o random_state =1
logistic_risco_credito

LogisticRegression(random_state=1)

class sklearn.linear_model.LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='deprecated', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)


https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [16]:
logistic_risco_credito.fit(X_risco_credito, y_risco_credito) # feito o treinamento

LogisticRegression(random_state=1)

* max_iter=100 é o número de vezes que vamos fazer o ajuste dos valores para nós encontrarmos os parâmetros ideais. 

* parâmetro solver='lbfgs', que é o algoritmo que será utilizado para de fato fazer o ajuste dos valores. 

padrão lbfgs, que é a descida do gradiente

* solver{‘lbfgs’, ‘liblinear’, ‘newton-cg’, ‘newton-cholesky’, ‘sag’, ‘saga’}, default=’lbfgs’
Algorithm to use in the optimization problem. Default is ‘lbfgs’. To choose a solver, you might want to consider the following aspects:

For small datasets, ‘liblinear’ is a good choice, whereas ‘sag’ and ‘saga’ are faster for large ones;

For multiclass problems, all solvers except ‘liblinear’ minimize the full multinomial loss;

‘liblinear’ can only handle binary classification by default. To apply a one-versus-rest scheme for the multiclass setting one can wrap it with the OneVsRestClassifier.

‘newton-cholesky’ is a good choice for n_samples >> n_features * n_classes, especially with one-hot encoded categorical features with rare categories. Be aware that the memory usage of this solver has a quadratic dependency on n_features * n_classes because it explicitly computes the full Hessian matrix.

* This class implements regularized logistic regression using the ‘liblinear’ library, ‘newton-cg’, ‘sag’, ‘saga’ and ‘lbfgs’ solvers. Note that regularization is applied by default. It can handle both dense and sparse input. Use C-ordered arrays or CSR matrices containing 64-bit floats for optimal performance; any other input format will be converted (and copied).

The ‘newton-cg’, ‘sag’, and ‘lbfgs’ solvers support only L2 regularization with primal formulation, or no regularization. The ‘liblinear’ solver supports both L1 and L2 regularization, with a dual formulation only for the L2 penalty. The Elastic-Net regularization is only supported by the ‘saga’ solver.

For multiclass problems, only ‘newton-cg’, ‘sag’, ‘saga’ and ‘lbfgs’ handle multinomial loss. ‘liblinear’ and ‘newton-cholesky’ only handle binary classification but can be extended to handle multiclass by using OneVsRestClassifier.

In [17]:
# verificar o parâmetro utilizado

print(logistic_risco_credito.get_params())


{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'deprecated', 'n_jobs': None, 'penalty': 'l2', 'random_state': 1, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [18]:
logistic_risco_credito.intercept_

array([-0.80855152])

In [20]:
print('equivale ao parâmetro b0 =  {}'.format(logistic_risco_credito.intercept_[0]))

equivale ao parâmetro b0 =  -0.8085515186482206


In [21]:
logistic_risco_credito.coef_

array([[-0.76706797,  0.23921064, -0.47989768,  1.12196145]])

In [23]:
print(f'achar os coeficientes: {logistic_risco_credito.coef_[0]}')

achar os coeficientes: [-0.76706797  0.23921064 -0.47989768  1.12196145]


In [24]:
# quatro valores, cada um para os seus atributos previsores

B1 - historia,  

B2 - divida,

B3 - garantias,

B4 - renda,

Fazermos algumas previsões




In [25]:
# história boa(0), dívida alta(0), garantias nenhuma(1), renda > 35 (2)
# história ruim(2) dívida alta(0), garantias adequada(0), renda < 15 (0)
previsoes1 = logistic_risco_credito.predict([[0,0,1,2], [2,0,0,0]])
previsoes1

array(['baixo', 'alto'], dtype=object)

In [26]:
# previsões do risco 