# Redução de dimensionalidade

In [50]:
# from google.colab import drive
# drive.mount('/content/drive')
# ambiente anaconda udemy
import os
DRIVE_DIRECTORY = "../25-Atributos"
DRIVE_DIRECTORY = os.path.join("", DRIVE_DIRECTORY)


In [6]:
DRIVE_DIRECTORY

'../25-Atributos'

In [7]:
# importar as bibliotecas

import pickle

from sklearn.decomposition import KernelPCA, PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split


## Redução de dimensionalidade

Neste exercício você vai utilizar a base de dados de cobertura vegetal mais uma vez, mas você já pode recuperar da pasta no Drive as variáveis `X` e `y` geradas no exercício anterior, que estão armazenadas no arquivo `cover_type_num.pkl`. Lembre-se, `X` contém os atributos numéricos depois de normalização, e `y` contém a variável alvo codificada com `LabelEncoder`.

In [8]:
with open(os.path.join(DRIVE_DIRECTORY, "cover_type_num.pkl"), "rb") as f:
    X, y = pickle.load(f)

In [9]:
X

array([[0.4477459 , 0.18333333, 0.30909091, ..., 0.66666667, 0.384     ,
        0.31482517],
       [0.42571721, 0.44444444, 0.34545455, ..., 0.90666667, 0.508     ,
        0.35160839],
       [0.2392418 , 0.18055556, 0.12727273, ..., 0.81333333, 0.536     ,
        0.04741259],
       ...,
       [0.59375   , 0.21944444, 0.34545455, ..., 0.66      , 0.34      ,
        0.20839161],
       [0.54559426, 0.16111111, 0.10909091, ..., 0.82      , 0.548     ,
        0.31888112],
       [0.40420082, 0.25277778, 0.23636364, ..., 0.76666667, 0.432     ,
        0.23230769]], shape=(10000, 10))

In [11]:
y

array([4, 4, 5, ..., 6, 4, 4], shape=(10000,))

Separe 25% dos dados para o split de teste, e restante para o treinamento.

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

Exiba o `shape` das variáveis `X`.

In [13]:
X_train.shape, X_test.shape  # 10 atributos, com 7500 linhas de treino e 2500 linhas de teste

((7500, 10), (2500, 10))

instanciar com 6 componentes (transformar 10 colunas em 6 colunas)

Pelo `shape` nós evidenciamos que estes dados possuem 10 atributos.

Instancie um PCA com 6 componentes, e aplique ele às variáveis `X` de treino e teste.


In [14]:
pca = PCA(n_components=6)

In [16]:
pca

,n_components,6
,copy,True
,whiten,False
,svd_solver,'auto'
,tol,0.0
,iterated_power,'auto'
,n_oversamples,10
,power_iteration_normalizer,'auto'
,random_state,None


In [17]:
pca.get_params()

{'copy': True,
 'iterated_power': 'auto',
 'n_components': 6,
 'n_oversamples': 10,
 'power_iteration_normalizer': 'auto',
 'random_state': None,
 'svd_solver': 'auto',
 'tol': 0.0,
 'whiten': False}

In [15]:
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [18]:
X_train_pca

array([[-0.31323708,  0.24190522, -0.06462298, -0.19878973, -0.18898878,
        -0.15432216],
       [-0.11399097,  0.00227971,  0.18541064, -0.17112884,  0.15667165,
         0.09723647],
       [-0.33115172, -0.08396722,  0.05412609,  0.05491544, -0.1225675 ,
         0.17131759],
       ...,
       [ 0.52203261,  0.61870271,  0.06951415,  0.21336151, -0.02852403,
         0.11538546],
       [-0.35001162, -0.3272663 , -0.10807471, -0.12735189, -0.10175675,
        -0.1587069 ],
       [-0.31351795,  0.37952367, -0.04572486, -0.12052121, -0.39255474,
        -0.18346823]], shape=(7500, 6))

In [19]:
X_test_pca

array([[-0.24321082,  0.152449  ,  0.0549741 ,  0.04578714, -0.09205015,
         0.09101738],
       [-0.2816137 , -0.3149199 , -0.00762466,  0.07605124, -0.15898847,
         0.28648658],
       [-0.34921706, -0.47812162, -0.1299906 ,  0.33678819,  0.02884416,
         0.25784521],
       ...,
       [ 0.56758005, -0.03856508,  0.27201134,  0.17127416, -0.02256414,
        -0.2220112 ],
       [-0.07213189,  0.00116064, -0.14095724, -0.14830776,  0.23364208,
         0.08077936],
       [ 0.53264444, -0.42072066, -0.04376457,  0.10661841, -0.01838018,
        -0.08216986]], shape=(2500, 6))

Exiba o `shape` das variáveis geradas.

agora temos 6 colunas no treino e teste

In [20]:
X_train_pca.shape, X_test_pca.shape

((7500, 6), (2500, 6))

Exiba a variância explicada por PC, e depois sua soma.

In [21]:
pca.explained_variance_ratio_ # variância de importância

array([0.38414421, 0.21396693, 0.09374258, 0.09046713, 0.08626326,
       0.06021123])

In [23]:
pca.explained_variance_ratio_.sum() # ^correto para 1

np.float64(0.9287953418126457)

In [24]:
# instanciar e treinar

Instancie e treine um classificador do tipo `RandomForestClassifier`, com `random_state=0`.

In [25]:
tree_classifier = RandomForestClassifier(random_state=0)
tree_classifier.fit(X_train_pca, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [26]:
tree_classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

### Gere predições com os dados de teste, e calcule a acurácia.

In [27]:
y_pred = tree_classifier.predict(X_test_pca)

In [28]:
accuracy_score(y_test, y_pred)

0.6756

In [30]:
y_pred # previsão

array([4, 4, 5, ..., 6, 6, 2], shape=(2500,))

In [32]:
print(f'acurácia do método de Random Forest (várias árvores de decisão) e pca : {accuracy_score(y_test, y_pred)*100:.2f}%') 
#Random Forest é um algoritmo de Machine Learning que constrói e combina várias árvores de decisão (floresta) 

acurácia do método de Random Forest (várias árvores de decisão) e pca : 67.56%


### Kernel PCA

Repita o exercício, agora com Kernel PCA, utilizando o mesmo número de componentes, e `kernel="rbf"`.

In [33]:
kpca = KernelPCA(n_components=6, kernel="rbf")
X_train_kpca = kpca.fit_transform(X_train)
X_test_kpca = kpca.transform(X_test)

In [34]:
kpca.get_params()

{'alpha': 1.0,
 'coef0': 1,
 'copy_X': True,
 'degree': 3,
 'eigen_solver': 'auto',
 'fit_inverse_transform': False,
 'gamma': None,
 'iterated_power': 'auto',
 'kernel': 'rbf',
 'kernel_params': None,
 'max_iter': None,
 'n_components': 6,
 'n_jobs': None,
 'random_state': None,
 'remove_zero_eig': False,
 'tol': 0}

In [35]:
tree_classifier = RandomForestClassifier(random_state=0)
tree_classifier.fit(X_train_kpca, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [36]:
tree_classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

In [37]:
# previsão com os dados de teste
y_pred = tree_classifier.predict(X_test_kpca)

In [38]:
y_pred

array([4, 4, 5, ..., 6, 6, 2], shape=(2500,))

In [39]:
accuracy_score(y_test, y_pred)

0.6712

In [40]:
print(f'acurácia do método de Random Forest (várias árvores de decisão) e kernel pca : {accuracy_score(y_test, y_pred)*100:.2f}%') 


acurácia do método de Random Forest (várias árvores de decisão) e kernel pca : 67.12%


### LDA

Mais uma vez repita o exercício, agora com LDA de 6 componentes.

In [41]:
lda = LinearDiscriminantAnalysis(n_components=6)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

In [42]:
lda.get_params()

{'covariance_estimator': None,
 'n_components': 6,
 'priors': None,
 'shrinkage': None,
 'solver': 'svd',
 'store_covariance': False,
 'tol': 0.0001}

In [43]:
tree_classifier = RandomForestClassifier(random_state=0)
tree_classifier.fit(X_train_lda, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [45]:
tree_classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

In [46]:
y_pred = tree_classifier.predict(X_test_lda)

In [47]:
y_pred

array([4, 4, 5, ..., 6, 6, 2], shape=(2500,))

In [48]:
accuracy_score(y_test, y_pred)

0.7332

In [49]:
print(f'acurácia do método de Random Forest (várias árvores de decisão) e LDA : {accuracy_score(y_test, y_pred)*100:.2f}%') 


acurácia do método de Random Forest (várias árvores de decisão) e LDA : 73.32%


lda com um resultado um pouquinho melhor