### Redução de Dimensionalidade => PCA (Principal Component Analys)

## Redução de dimensionalidade

### Preparacão da base de dados

In [114]:
# ambiente do anaconda Udemy

In [58]:
import pandas as pd
# material da escola, o outro do início das aulas foi "baseado em dados retirados da internet atuais".
arquivo = '../24-Dados_desbalanceados/census.csv'

base_census = pd.read_csv(arquivo)
base_census.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K


In [59]:
# dados da pessoa, para prever a renda, income

In [60]:
base_census['income'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [61]:
X_census = base_census.iloc[:, 0:14].values
X_census

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      shape=(32561, 14), dtype=object)

In [62]:
#colunas de base para achar o income
list(base_census.iloc[:,0:14].columns)

['age',
 'workclass',
 'final-weight',
 'education',
 'education-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital-gain',
 'capital-loos',
 'hour-per-week',
 'native-country']

In [63]:
y_census = base_census.iloc[:, 14].values
y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      shape=(32561,), dtype=object)

In [64]:
list(base_census.iloc[:, 14:15].columns)

['income']

## Para os atributos categóricos

In [65]:
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

In [66]:
# aplicação a cada um dos atributos

X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:,1])
X_census[:,3] = label_encoder_education.fit_transform(X_census[:,3])
X_census[:,5] = label_encoder_marital.fit_transform(X_census[:,5])
X_census[:,6] = label_encoder_occupation.fit_transform(X_census[:,6])
X_census[:,7] = label_encoder_relationship.fit_transform(X_census[:,7])
X_census[:,8] = label_encoder_race.fit_transform(X_census[:,8])
X_census[:,9] = label_encoder_sex.fit_transform(X_census[:,9])
X_census[:,13] = label_encoder_country.fit_transform(X_census[:,13])

In [67]:
X_census[0] # dos atributos categoricos para os atributos numéricos 

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 39], dtype=object)

### Padronizar os dados para deixar todos na mesma escala

In [68]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
X_census = scaler_census.fit_transform(X_census)

In [69]:
X_census[:10] # os valores foram padronizados com a mesma ordem. 

array([[ 0.03067056,  2.15057856, -1.06361075, -0.33543693,  1.13473876,
         0.92163395, -1.3178091 , -0.27780504,  0.39366753,  0.70307135,
         0.1484529 , -0.21665953, -0.03542945,  0.29156857],
       [ 0.83710898,  1.46373585, -1.008707  , -0.33543693,  1.13473876,
        -0.4062122 , -0.60838662, -0.90018084,  0.39366753,  0.70307135,
        -0.14592048, -0.21665953, -2.22215312,  0.29156857],
       [-0.04264203,  0.09005041,  0.2450785 ,  0.18133163, -0.42005962,
        -1.73405835, -0.1354383 , -0.27780504,  0.39366753,  0.70307135,
        -0.14592048, -0.21665953, -0.03542945,  0.29156857],
       [ 1.05704673,  0.09005041,  0.42580136, -2.40251115, -1.19745882,
        -0.4062122 , -0.1354383 , -0.90018084, -1.96262077,  0.70307135,
        -0.14592048, -0.21665953, -0.03542945,  0.29156857],
       [-0.77576787,  0.09005041,  1.40817572, -0.33543693,  1.13473876,
        -0.4062122 ,  0.81045833,  2.21169816, -1.96262077, -1.42233076,
        -0.14592048, -0.21

In [70]:
from sklearn.model_selection import train_test_split
X_census_treinamento, X_census_teste, y_census_treinamento, y_census_teste = train_test_split(X_census, 
                                                                                              y_census, 
                                                                                              test_size=0.15, 
                                                                                              random_state=0)

In [71]:
X_census_treinamento.shape, X_census_teste.shape # técnica para reduzir a dimensionalidade

((27676, 14), (4885, 14))

### 14 atributos no total, e vamos reduzir a dimensionalidade, e deixar com 6 atributos apenas. 

### Vamos aplicar a classificação e fazer o comparativo dos resultados para nós verificarcmos se a aplicação do PCA vai melhorar o acurácia do algoritmo.

## PCA (Principal component analysis)

In [72]:
from sklearn.decomposition import PCA

In [73]:
pca = PCA(n_components=6) # instanciamos (objeto concreto) para número de componentes que indica quantos atributos que nós vamos gerar. 
# verificas os atributos com as datas de nascimento. Cria um novo atributo combinando a idade e o nascimento, por exemplo
# assim os atributos mais correlacionados serão UNIDOS;

ver os atributos mais correlacionados 

In [74]:
# transformar os dados no x treinamento e teste
X_census_treinamento_pca = pca.fit_transform(X_census_treinamento) # algoritmo adpatou os dados


X_census_testes_pca = pca.transform(X_census_teste) # depois transforma


In [75]:
X_census_treinamento_pca.shape, X_census_testes_pca.shape 

# mudança para 6 atributos, cobinando os 14 atributos e gera novos 6 atributos

((27676, 6), (4885, 6))

In [76]:
X_census_treinamento[:4]

array([[-0.92239303,  1.46373585,  1.84273483,  0.18133163, -0.42005962,
        -0.4062122 , -0.60838662, -0.90018084,  0.39366753,  0.70307135,
        -0.14592048, -0.21665953, -0.03542945,  0.29156857],
       [-0.84908045,  0.09005041,  0.19630465,  1.21486874, -0.03136003,
        -0.4062122 , -0.60838662, -0.90018084,  0.39366753,  0.70307135,
        -0.14592048, -0.21665953,  3.20416118,  0.29156857],
       [ 1.42360965, -1.28363502,  2.83572992, -0.33543693,  1.13473876,
        -0.4062122 ,  0.81045833, -0.90018084, -1.96262077,  0.70307135,
        -0.14592048, -0.21665953, -0.03542945,  0.29156857],
       [ 0.25060831, -1.28363502,  0.72342797,  1.21486874, -0.03136003,
        -0.4062122 ,  1.04693249, -0.90018084,  0.39366753,  0.70307135,
        -0.14592048, -0.21665953,  0.93644774,  0.29156857]])

In [77]:
# verificar a variância dos dados

In [78]:
pca.explained_variance_ratio_

array([0.151561  , 0.10109701, 0.08980379, 0.08076277, 0.07627678,
       0.07357646])

In [79]:
#14 atiributo para 1: (0.151561) teremos 15% das variáveis explicáveis 

In [80]:
sum(list(pca.explained_variance_ratio_))

np.float64(0.5730778058904425)

In [81]:
sum(list(pca.explained_variance_ratio_)[:2]) # segunda coluna 25% dos dados explicado das variáveis

np.float64(0.25265800390613913)

In [82]:
sum((pca.explained_variance_ratio_))

np.float64(0.5730778058904425)

In [83]:
sum(list(pca.explained_variance_ratio_)[:3]) # terceira coluna 34% dos dados explicado das variáveis

np.float64(0.3424617913793744)

In [84]:
sum(list(pca.explained_variance_ratio_))*100 #57%  pouco ainda de interesse, explicação nas variáveis

np.float64(57.307780589044256)

In [85]:
pca.explained_variance_ratio_.sum()

np.float64(0.5730778058904425)

In [86]:

# teste 14 atributos
# transformar os dados no x treinamento e teste
X_census_treinamento_pca = pca.fit_transform(X_census_treinamento) # algoritmo adpatou os dados
X_census_testes_pca = pca.transform(X_census_teste) # depois transforma

print(X_census_treinamento_pca.shape, X_census_testes_pca.shape)

print(X_census_treinamento[:4])

print(pca.explained_variance_ratio_)
print(sum(list(pca.explained_variance_ratio_)))
print(f' segunda coluna dos dados explicado das variáveis: {sum(list(pca.explained_variance_ratio_)[:2])} ')
print(sum(list(pca.explained_variance_ratio_)[:2])) # segunda coluna dos dados explicado das variáveis
print(sum((pca.explained_variance_ratio_)))

print(f' terceira coluna  dos dados explicado das variáveis {sum(list(pca.explained_variance_ratio_)[:3])}') # terceira coluna  dos dados explicado das variáveis

print(f'interesse total, explicação nas variáveis {sum(list(pca.explained_variance_ratio_))*100} %') # %  pouco ainda de interesse, explicação nas variáveis
print(pca.explained_variance_ratio_.sum())

#100% todas as variáveis, tem 100% de exolicação delas


(27676, 6) (4885, 6)
[[-0.92239303  1.46373585  1.84273483  0.18133163 -0.42005962 -0.4062122
  -0.60838662 -0.90018084  0.39366753  0.70307135 -0.14592048 -0.21665953
  -0.03542945  0.29156857]
 [-0.84908045  0.09005041  0.19630465  1.21486874 -0.03136003 -0.4062122
  -0.60838662 -0.90018084  0.39366753  0.70307135 -0.14592048 -0.21665953
   3.20416118  0.29156857]
 [ 1.42360965 -1.28363502  2.83572992 -0.33543693  1.13473876 -0.4062122
   0.81045833 -0.90018084 -1.96262077  0.70307135 -0.14592048 -0.21665953
  -0.03542945  0.29156857]
 [ 0.25060831 -1.28363502  0.72342797  1.21486874 -0.03136003 -0.4062122
   1.04693249 -0.90018084  0.39366753  0.70307135 -0.14592048 -0.21665953
   0.93644774  0.29156857]]
[0.151561   0.10109701 0.08980379 0.08076277 0.07627678 0.07357646]
0.5730778058904425
 segunda coluna dos dados explicado das variáveis: 0.25265800390613913 
0.25265800390613913
0.5730778058904425
 terceira coluna  dos dados explicado das variáveis 0.3424617913793744
interesse tot

In [87]:

# teste para a explicação mais próxima de 1
pca = PCA(n_components=8) # 8 variáveis ou compontentes ver a porcentagem para explicar as variáveis. 
# transformar os dados no x treinamento e teste
X_census_treinamento_pca = pca.fit_transform(X_census_treinamento) # algoritmo adpatou os dados
X_census_testes_pca = pca.transform(X_census_teste) # depois transforma

print(X_census_treinamento_pca.shape, X_census_testes_pca.shape)

print(X_census_treinamento[:4])

print(pca.explained_variance_ratio_)
print(sum(list(pca.explained_variance_ratio_)))
print(f' segunda coluna dos dados explicado das variáveis: {sum(list(pca.explained_variance_ratio_)[:2])} ')
print(sum(list(pca.explained_variance_ratio_)[:2])) # segunda coluna dos dados explicado das variáveis
print(sum((pca.explained_variance_ratio_)))

print(f' terceira coluna  dos dados explicado das variáveis {sum(list(pca.explained_variance_ratio_)[:3])}') # terceira coluna  dos dados explicado das variáveis

print(f'interesse total, explicação nas variáveis {sum(list(pca.explained_variance_ratio_))*100} %') # %  pouco ainda de interesse, explicação nas variáveis
print(pca.explained_variance_ratio_.sum())

#8 variáveis ou compontentes explicam 70% das variáveis


(27676, 8) (4885, 8)
[[-0.92239303  1.46373585  1.84273483  0.18133163 -0.42005962 -0.4062122
  -0.60838662 -0.90018084  0.39366753  0.70307135 -0.14592048 -0.21665953
  -0.03542945  0.29156857]
 [-0.84908045  0.09005041  0.19630465  1.21486874 -0.03136003 -0.4062122
  -0.60838662 -0.90018084  0.39366753  0.70307135 -0.14592048 -0.21665953
   3.20416118  0.29156857]
 [ 1.42360965 -1.28363502  2.83572992 -0.33543693  1.13473876 -0.4062122
   0.81045833 -0.90018084 -1.96262077  0.70307135 -0.14592048 -0.21665953
  -0.03542945  0.29156857]
 [ 0.25060831 -1.28363502  0.72342797  1.21486874 -0.03136003 -0.4062122
   1.04693249 -0.90018084  0.39366753  0.70307135 -0.14592048 -0.21665953
   0.93644774  0.29156857]]
[0.151561   0.10109701 0.08980379 0.08076277 0.07627678 0.07357646
 0.06772289 0.06690789]
0.7077085943199318
 segunda coluna dos dados explicado das variáveis: 0.25265800390613913 
0.25265800390613913
0.7077085943199318
 terceira coluna  dos dados explicado das variáveis 0.3424617

### utilizar o componente de algoritmo de classificação, ao invés de nós passarmos a base de dados com 14 registros, vamos somente passar com 8 registros. 

### usar o algoritmo random forest classifier.

In [88]:
from sklearn.ensemble import RandomForestClassifier

In [89]:
random_forest_census_pca = RandomForestClassifier(n_estimators=40, random_state=0, criterion = 'entropy')
random_forest_census_pca.fit(X_census_treinamento_pca, y_census_treinamento) # treinamento para gerar as árvores
# gera as 40 árvores

,n_estimators,40
,criterion,'entropy'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [90]:
random_forest_census_pca.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 40,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

### gerar as previsões e verificar os resultados 


RandomForestClassifier(n_estimators=40, random_state=0, criterion='entropy')

1️⃣ n_estimators=40

Quantidade de árvores que o Random Forest vai criar.

Mais árvores → melhor desempenho, mais lento.

Aqui são 40 árvores.

2️⃣ random_state=0

Define a semente aleatória.

Serve para que o resultado seja reproduzível (igual toda vez que rodar).

3️⃣ criterion='entropy'

Define como cada árvore decide onde cortar os dados.

'entropy' → usa ganho de informação (Information Gain)

'gini' → é o padrão e costuma ser um pouco mais rápido

Aqui o escolhido foi entropy, que tende a separar melhor classes desbalanceadas, mas pode ser um pouco mais lento.

In [91]:
# as previsões

previsoes = random_forest_census_pca.predict(X_census_testes_pca)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      shape=(4885,), dtype=object)

In [92]:
# respostas reais
y_census_teste

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      shape=(4885,), dtype=object)

In [93]:
from sklearn.metrics import accuracy_score
accuracy_score(y_census_teste, previsoes)

0.8343909928352098

In [94]:
# cálculo da acurácia
print(f'acurácia do random forest {accuracy_score(y_census_teste, previsoes)*100} %')

acurácia do random forest 83.43909928352097 %


In [95]:
# o ideal é sempre analisar a atribuição ou o nível de atribuição, a acurácia e o tempo de processamento

#### kernel parecido com o que é usado no algoritmo svm

## Kernel PCA

In [96]:
from sklearn.decomposition import KernelPCA

In [97]:
kpca = KernelPCA(n_components=8, kernel='rbf') # vamos passar novamente para 8 atributos, ou colunas

X_census_treinamento_kpca = kpca.fit_transform(X_census_treinamento) # treinamento
X_census_teste_kpca = kpca.transform(X_census_teste) # teste

# parametro adicional, kernel linear 


https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.KernelPCA.html

https://scikit-learn.org/stable/auto_examples/decomposition/plot_kernel_pca.html

kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘cosine’, ‘precomputed’} or callable, default=’linear’

Kernel used for PCA.

In [98]:
### rbf, problemas não linearmente separáveis

#### kernels para aumentar a dimensionalidade dos dados

In [99]:
X_census_treinamento_kpca.shape, X_census_teste_kpca.shape 

# não foram aplicadas as seleções de atributos
# foram combinados os atributos
# gerando os atributos novos, com valores diferentes
# 14 atributos sendo reduzidos para 8 atributos

((27676, 8), (4885, 8))

In [100]:
X_census_treinamento_kpca

array([[ 0.18894283,  0.05517031, -0.08653531, ...,  0.41350358,
         0.06383854, -0.25147161],
       [ 0.16165577, -0.07855932, -0.03858728, ..., -0.01994034,
        -0.00338877, -0.29452204],
       [-0.085163  , -0.27486159,  0.12920466, ...,  0.19029531,
         0.04692292,  0.13187157],
       ...,
       [-0.27872683,  0.40033469,  0.20104327, ..., -0.17392304,
        -0.16108872,  0.00683154],
       [ 0.21829898, -0.12392098, -0.02312817, ..., -0.12231089,
         0.33364887,  0.25177643],
       [ 0.24961467,  0.42418174,  0.12141394, ..., -0.00408799,
        -0.18258341, -0.08239723]], shape=(27676, 8))

In [101]:
from sklearn.ensemble import RandomForestClassifier

# número de árvores :40
# impureza de geni entropy
random_forest_census_kpca = RandomForestClassifier(n_estimators = 40, 
                                                   criterion = 'entropy', 
                                                   random_state = 0)

random_forest_census_kpca.fit(X_census_treinamento_kpca, y_census_treinamento) # treinamento

,n_estimators,40
,criterion,'entropy'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [102]:
random_forest_census_kpca.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 40,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

🌲 n_estimators = 40

É a quantidade de árvores na floresta.
Mais árvores geralmente deixam o modelo mais estável, mas consomem mais tempo.
Com 40, você tem um equilíbrio bom entre velocidade e performance.
Número de árvores na floresta. Mais árvores → modelo mais estável (e mais lento).
40 árvores.

🧮 criterion = 'entropy'

Define como cada árvore decide onde “cortar” os dados (os splits).

entropy → usa o conceito de entropia da teoria da informação (igual no ID3).
É um critério um pouco mais exigente, buscando dividir os dados criando nós mais “puros”.

(Se fosse gini, seria um cálculo mais simples, mas ambos funcionam bem.)

Mede a qualidade da divisão usando entropia (informação).

Alternativa ao padrão "gini". Normalmente gera splits um pouco mais “puros”.


🎲 random_state = 0

Garante que o resultado seja sempre igual para rodar o código.

É como travar a semente da aleatoriedade.

Isso é ótimo para reproduzir experimento

Garante repetibilidade. Mantém os mesmos resultados se você rodar de novo.

fit(...)

Treina o modelo usando os dados transformados pelo KPCA (X_census_treinamento_kpca) e os rótulos (y_census_treinamento).



In [103]:
previsoes = random_forest_census_kpca.predict(X_census_teste_kpca)
previsoes  #previsores

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      shape=(4885,), dtype=object)

In [104]:
# comparar com as variáveis 

y_census_teste

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      shape=(4885,), dtype=object)

In [105]:
from sklearn.metrics import accuracy_score
accuracy_score(y_census_teste, previsoes)

0.826202661207779

In [106]:
print(f'Acurácia {accuracy_score(y_census_teste, previsoes)*100} %')

Acurácia 82.6202661207779 %


In [107]:
#kernel pca tem que fazer vários testes, pois há muitas variações

# 29.7)  LDA (Linear discriminant analysis)

Supervisionado: Aprendendo com o Professor

O modelo é treinado com pares de dados (Entrada e Saída desejada). Ele usa a Saída (rótulo) para corrigir seus erros a cada passo do treino, como um aluno com um gabarito.

### LDA é uma sigla com múltiplos significados, incluindo Análise Discriminante Linear (em Machine Learning, para classificação e redução de dimensionalidade)

Supervisionado e baseado na classe

os demais processos (PCA) não necessitam da classe. Nos anteriores PCA passamos o atributo previsores, para fazer o fit.

neste agora faremos a classe

classe é o income

In [108]:
unique_count = base_census['income'].nunique()
print(unique_count)

2


In [109]:
print(base_census['income'].unique())

[' <=50K' ' >50K']


In [110]:
contagem_classes = base_census['income'].value_counts()
print(contagem_classes)

income
<=50K    24720
>50K      7841
Name: count, dtype: int64


In [115]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components = 8) # número de componentes, que desejamos reduzir as colunas de 14 para 8 colunas

https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html



_sklearn.discriminant_analysis.LinearDiscriminantAnalysis(solver='svd', shrinkage=None, priors=None, n_components=None, store_covariance=False, tol=0.0001, covariance_estimator=None)_


* solver	

'svd'	=> Define o método usado para calcular a matriz de dispersão. As opções são:

'svd' => (Valor Padrão)	Não calcula explicitamente a matriz de covariância. Recomendado para dados com muitas features (colunas), pois é o mais robusto numericamente.

'lsqr'	=> Solução por Mínimos Quadrados. Pode ser usado com shrinkage. Mais rápido que o svd.

'eigen' => 	Decomposição por Autovalores/Autovetores. Funciona com shrinkage.

* shrinkage =>	None	Aplica a técnica de shrinkage (encolhimento) à matriz de covariância. Usada principalmente quando há poucos dados ou muitas features.

None (Padrão) => Não aplica shrinkage.
    
'auto'	=> O algoritmo calcula o melhor fator de shrinkage (apenas com solver='lsqr' ou solver='eigen').

float (0 a 1) =>	Define um fator de shrinkage constante manualmente.

* priors	None =>	Probabilidades a priori de cada classe.

None (Padrão) =>	As probabilidades são estimadas a partir da frequência relativa das classes nos dados de treinamento.

array-like	=> Uma lista de probabilidades fornecida pelo usuário (deve somar 1).

* n_components

None =>	O número de componentes que o LDA usará como dimensionalidade reduzida.

None (Padrão) =>	O valor máximo (o número de classes - 1) é usado.

int	=> Permite especificar o número de dimensões desejadas para a redução.

* store_covariance

False	=> Controla se a matriz de covariância deve ser explicitamente calculada e armazenada após o ajuste.

False (Padrão)	=> Não armazena a matriz, economizando memória.

True => 	Calcula e armazena a matriz de covariância para inspeção posterior (acessível via .covariance_).

* tol

0.0001 =>	Tolerância absoluta usada para ajudar a determinar o ranking de uma matriz de covariância. Afeta a forma como a regularização é aplicada internamente.

* covariance_estimator	

None	=> Um objeto estimator usado para estimar a matriz de covariância, como sklearn.covariance.EmpiricalCovariance.

None (Padrão) => As estimativas padrão do LDA são usadas. É usado principalmente quando se deseja uma estimativa de covariância mais robusta.

In [116]:
lda.get_params()

{'covariance_estimator': None,
 'n_components': 8,
 'priors': None,
 'shrinkage': None,
 'solver': 'svd',
 'store_covariance': False,
 'tol': 0.0001}

In [122]:
# treinamento e geração dos novos valores:

# preditores e respostas esperadas:

# X_census_treinamento_lda = lda.fit_transform(X_census_treinamento, y_census_treinamento)
# X_census_teste_lda = lda.transform(X_census_teste) # neste caso não passamos as respostas esperadas (no caso do teste)

# deu erro: ValueError: n_components cannot be larger than min(n_features, n_classes - 1).
# a classe não pode ser maior que as 14 colunas (n_features)
# na verdade só temos 2 classes, que no caso é o income => [' <=50K' ' >50K']



# min(n_features, n_classes =2  - 1)

# (14,1)

#assim, o n_components não pode ser maior do que 1 (classe = 2 e subtrai ele por -1 => 1)

### Não conseguiremos fazer a redução de dimensionamento de 14 para 8 atributos.  

como temos somente 2 classes na resposta (income), só podemos fazer a redução de dimensionalidade de 14 atributos para somente 1 atributo.  

se fosse 3 classes seria uma redução para 2 atributos.

## n_classes - 1,limitado pela quantidade de classes

In [123]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components = 1) # número de componentes, que desejamos reduzir as colunas de 14 para 8 colunas


In [124]:
lda.get_params()

{'covariance_estimator': None,
 'n_components': 1,
 'priors': None,
 'shrinkage': None,
 'solver': 'svd',
 'store_covariance': False,
 'tol': 0.0001}

In [125]:
X_census_treinamento_lda = lda.fit_transform(X_census_treinamento, y_census_treinamento)
X_census_teste_lda = lda.transform(X_census_teste) # neste caso não passamos as respostas esperadas (no caso do teste)

In [126]:
X_census_treinamento_lda.shape, X_census_teste_lda.shape

((27676, 1), (4885, 1))

In [131]:
X_census_treinamento_lda # treinamento com um atributo

array([[ 0.30226006],
       [-0.64945145],
       [-1.57912192],
       ...,
       [ 1.37887999],
       [-2.44698101],
       [ 0.19212323]], shape=(27676, 1))

In [130]:
X_census_teste_lda 

array([[ 0.73054783],
       [ 0.07265437],
       [-0.60947027],
       ...,
       [ 1.71469259],
       [-0.43978213],
       [-1.11869646]], shape=(4885, 1))

In [132]:
from sklearn.ensemble import RandomForestClassifier
random_forest_census_lda = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)
random_forest_census_lda.fit(X_census_treinamento_lda, y_census_treinamento)

,n_estimators,40
,criterion,'entropy'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [133]:
random_forest_census_lda.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 40,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

* n_estimators	40	Define que o modelo será construído a partir de 40 Árvores de Decisão individuais. O resultado final da classificação será a votação majoritária dessas 40 árvores.

* criterion	'entropy'	Define a função que mede a qualidade da divisão em cada nó da árvore. 'entropy' (Entropia) visa maximizar a informação ganha em cada divisão.

* random_state	0	Garante que o processo de criação (seleção aleatória de dados e features) seja reproduzível. Se você rodar o código novamente, obterá exatamente as mesmas árvores e o mesmo resultado.

- n_estimators	Efeito no Modelo

- Baixo (ex: 10-30)	Rápido de treinar, mas instável. O modelo pode não ter diversidade suficiente e o erro de generalização pode ser alto.

- Médio (ex: 50-200)	Bom equilíbrio. A performance geralmente se estabiliza. É o ponto onde você deve começar a testar.

- Alto (ex: 500+)	Melhor performance marginal. O ganho de performance é mínimo ou nulo, mas o tempo de treinamento e de previsão é significativamente maior.

In [134]:
# previsão

In [135]:
previsoes = random_forest_census_lda.predict(X_census_teste_lda)
previsoes

array([' <=50K', ' >50K', ' <=50K', ..., ' >50K', ' >50K', ' >50K'],
      shape=(4885,), dtype=object)

In [136]:
y_census_teste

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      shape=(4885,), dtype=object)

In [137]:
from sklearn.metrics import accuracy_score
accuracy_score(y_census_teste, previsoes)

0.7334698055271238

In [140]:
print(f'Acurácia do LDA: {accuracy_score(y_census_teste, previsoes)*100:.2f} %') # previsão, comparar com o teste real e a previsão

Acurácia do LDA: 73.35 %


In [142]:
# diminuiu para 1 atributo, a previsão, por isso o baixo redimento e previsibilidade.

# classe, baseado em muitas classes, como objetos e imagens.