# 29.2) exercício de atributos

In [74]:
# from google.colab import drive
# drive.mount('/content/drive')
import os
DRIVE_DIRECTORY = "/home/fabiene/Documentos/Fabiene/UDEMY_ML/Machine_Learning_Udemy/10-Redes_neurais_artificiais/exercicios/novo"


no linux find -name "cov_types.csv"

./Documentos/Fabiene/UDEMY_ML/Machine_Learning_Udemy/10-Redes_neurais_artificiais/exercicios/novo/cov_types.csv

In [75]:
#biblioteca 

import numpy as np
import pandas as pd
import pickle

from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.feature_selection import VarianceThreshold
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

## Seleção de atributos
### Base de dados cobertura vegetal

Neste exercício você vai mais uma vez utilizar a base de dados cobertura vegetal.

Carregue o arquivo csv salvo na pasta do Drive. Visualize o DataFrame resultante.

In [76]:
base = pd.read_csv(os.path.join(DRIVE_DIRECTORY, 'cov_types.csv'))
base.tail(5)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
9995,2917.0,90.0,9.0,247.0,25.0,4095.0,235.0,225.0,121.0,3901.0,0,28,Lodgepole Pine
9996,3015.0,38.0,8.0,361.0,74.0,4846.0,220.0,223.0,138.0,1611.0,0,28,Lodgepole Pine
9997,3052.0,79.0,19.0,90.0,11.0,1003.0,241.0,203.0,85.0,1490.0,2,22,Spruce/Fir
9998,2958.0,58.0,6.0,319.0,19.0,2468.0,225.0,227.0,137.0,2280.0,0,28,Lodgepole Pine
9999,2682.0,91.0,13.0,162.0,32.0,1369.0,240.0,219.0,108.0,1661.0,2,10,Lodgepole Pine


# colunas categoricas: Cover_Type

Desta vez você vai remover as colunas categóricas, pois a variância é mais informativa para atributos numéricos.


Primeiro, separe o nome das colunas em uma variável `colunas`, mas lembre-se de remover as 3 últimas colunas (que correspondem às 2 variáveis categóricas, mais a variável alvo).

    

In [77]:
print(base.columns)

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area', 'Soil_Type',
       'Cover_Type'],
      dtype='object')


In [78]:
columns = base.columns[:-3]
columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points'],
      dtype='object')

Agora crie as variáveis `X` e `y`, no formato de NumPy array, mas não inclua as variáveis categóricas em `X`.

In [79]:
X = base.iloc[:, :-3].values # previsores 
y = base.iloc[:, -1].values

Exiba os valores de X.

In [80]:
X

array([[2767.,   66.,   17., ...,  204.,   96., 2251.],
       [2724.,  160.,   19., ...,  240.,  127., 2514.],
       [2360.,   65.,    7., ...,  226.,  134.,  339.],
       ...,
       [3052.,   79.,   19., ...,  203.,   85., 1490.],
       [2958.,   58.,    6., ...,  227.,  137., 2280.],
       [2682.,   91.,   13., ...,  219.,  108., 1661.]], shape=(10000, 10))

In [81]:
y # categórico

array(['Lodgepole Pine', 'Lodgepole Pine', 'Ponderosa Pine', ...,
       'Spruce/Fir', 'Lodgepole Pine', 'Lodgepole Pine'],
      shape=(10000,), dtype=object)

# normalizar na escala entre 0 e 1

In [82]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.4477459 , 0.18333333, 0.30909091, ..., 0.66666667, 0.384     ,
        0.31482517],
       [0.42571721, 0.44444444, 0.34545455, ..., 0.90666667, 0.508     ,
        0.35160839],
       [0.2392418 , 0.18055556, 0.12727273, ..., 0.81333333, 0.536     ,
        0.04741259],
       ...,
       [0.59375   , 0.21944444, 0.34545455, ..., 0.66      , 0.34      ,
        0.20839161],
       [0.54559426, 0.16111111, 0.10909091, ..., 0.82      , 0.548     ,
        0.31888112],
       [0.40420082, 0.25277778, 0.23636364, ..., 0.76666667, 0.432     ,
        0.23230769]], shape=(10000, 10))

Codifique os dados de `y` utilizando `LabelEncoder`.

## codificar os dados de y com o LabelEncoder

In [83]:
y

array(['Lodgepole Pine', 'Lodgepole Pine', 'Ponderosa Pine', ...,
       'Spruce/Fir', 'Lodgepole Pine', 'Lodgepole Pine'],
      shape=(10000,), dtype=object)

In [84]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y

array([4, 4, 5, ..., 6, 4, 4], shape=(10000,))

In [85]:
DRIVE_DIRECTORY2=""

In [86]:
# salvar o arquivo nesta forma 
with open(os.path.join(DRIVE_DIRECTORY2, "cover_type_num.pkl"), "wb") as f:
    pickle.dump((X, y), f)

### Variância

Exiba a variância dos dados preditores. DICA: ao invés de um implementar um loop, você pode usar o método `var` com o parâmetro `axis=0`, que vai calcular a variância nas colunas.

In [87]:
X.var(axis=0)

array([0.02040914, 0.09559695, 0.01843345, 0.02361915, 0.0068116 ,
       0.05098971, 0.01885846, 0.01751286, 0.02366312, 0.03431677])

In [88]:
len(base.columns[:-3]) # X

10

Perceba que temos 10 valores, correspondentes às 10 colunas numéricas do dataset.

Crie um seletor do tipo `VarianceThreshold` utilizando `threshold=0.02`. Exiba o `shape` do resultado.

remove features com variância baixa, ou seja, que quase não variam e por isso não ajudam o modelo.

remove colunas com variância menor que 0.02.

In [89]:
selector = VarianceThreshold(threshold=0.02)
X_variance = selector.fit_transform(X)
X_variance.shape

(10000, 6)

In [90]:
print(f'foram selecionados {X_variance.shape[1]} colunas')

foram selecionados 6 colunas


Exiba as variâncias armazenadas no seletor.

In [91]:
selector.variances_

array([0.02040914, 0.09559695, 0.01843345, 0.02361915, 0.0068116 ,
       0.05098971, 0.01885846, 0.01751286, 0.02366312, 0.03431677])

Perceba que os resultados são os mesmos que você calculou antes.

Recupere os índices das colunas que foram selecionadas.



In [92]:
indices = np.where(selector.variances_ > 0.02)
indices

(array([0, 1, 3, 5, 8, 9]),)

In [93]:
for i in range(X.shape[1]):
   print(f"Atributo {i+1}: {base.columns[i]}")
   print(f"Variância do atributo, ou extração da variância: {X[:,i].var():.2f}")
   #print("Variância escalonada")
   if X[:,i].var() > 0.02:
       # Verde
       print(f"Variância do atributo escalonado ({base.columns[i]}): \033[32m{X[:,i].var():.5f}\033[0m")       
   else:        
       print(f"Variância do atributo escalonado ({base.columns[i]}): {X[:,i].var():.5f}")
   print()

    
# \033[92m → verde
# \033[0m → volta à cor normal
# \033[32m → verde

Atributo 1: Elevation
Variância do atributo, ou extração da variância: 0.02
Variância do atributo escalonado (Elevation): 0.02041

Atributo 2: Aspect
Variância do atributo, ou extração da variância: 0.10
Variância do atributo escalonado (Aspect): 0.09560

Atributo 3: Slope
Variância do atributo, ou extração da variância: 0.02
Variância do atributo escalonado (Slope): 0.01843

Atributo 4: Horizontal_Distance_To_Hydrology
Variância do atributo, ou extração da variância: 0.02
Variância do atributo escalonado (Horizontal_Distance_To_Hydrology): 0.02362

Atributo 5: Vertical_Distance_To_Hydrology
Variância do atributo, ou extração da variância: 0.01
Variância do atributo escalonado (Vertical_Distance_To_Hydrology): 0.00681

Atributo 6: Horizontal_Distance_To_Roadways
Variância do atributo, ou extração da variância: 0.05
Variância do atributo escalonado (Horizontal_Distance_To_Roadways): 0.05099

Atributo 7: Hillshade_9am
Variância do atributo, ou extração da variância: 0.02
Variância do atr

Qual o nome das colunas selecionadas?

In [94]:
columns[indices]

Index(['Elevation', 'Aspect', 'Horizontal_Distance_To_Hydrology',
       'Horizontal_Distance_To_Roadways', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points'],
      dtype='object')

Agora, utilize os dados em `X_variance` e `y` para separar os dados em split de treinamento, e de teste (com `test_size=0.25`).

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X_variance,
                                                    y, 
                                                    test_size=0.25, 
                                                    random_state=0)

In [96]:
X_train.shape, X_test.shape  # treino 75% e teste 25%

((7500, 6), (2500, 6))

Crie uma instância do tipo `RandomForestClassifier`, com os argumentos padrão e `random_state=0`. Treine o algoritmo com os dados de treinamento.

In [97]:
tree_classifier = RandomForestClassifier(random_state=0)
tree_classifier.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [98]:
tree_classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

Faça predições para os dados de teste, e calcule a acurácia.

In [99]:
y_pred = tree_classifier.predict(X_test) # preditor

In [100]:
accuracy_score(y_test, y_pred)

0.7712

In [101]:
print(f'Acurácia {accuracy_score(y_test, y_pred)*100:.2f} %')

Acurácia 77.12 %


Veja que neste caso, o algoritmo ficou um pouco pior que aquele treinado na **Parte 1**. Isso indica que, por mais que tenhamos acentuado os atributos com maior variância, e potencialmente por isso mais poder discriminativo, tanto os atributos de menor variância quanto os atributos categóricos têm influência não desprezível na classificação das árvores.

In [102]:
# ficou baixo em comparação com outro método => a acurácia ficou maior

#=> M26-Exercicio_Tratamento_de_dados_desbalanceados.ipynb

### Extra tree

Agora crie e treine uma instância do seletor `ExtraTreesClassifier`. Utilize todos os dados, ou seja, as variáveis `X`e `y`, na fase de seleção de atributos.

In [103]:
selector = ExtraTreesClassifier()
selector.fit(X, y)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,False
,oob_score,False


In [104]:
selector.get_params()

{'bootstrap': False,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

Exiba as importâncias determinadas pelo algoritmo.

In [105]:
selector.feature_importances_

array([0.30522361, 0.06814081, 0.06333626, 0.08039422, 0.0747249 ,
       0.10671007, 0.06488601, 0.0676884 , 0.06340912, 0.10548661])

Com auxílio do NumPy, recupere os índices com importância maior que $0.07$.

In [106]:
indices = np.where(selector.feature_importances_ > 0.07)
indices

(array([0, 3, 4, 5, 9]),)

Que atributos foram selecionados?

In [107]:
columns[indices]

Index(['Elevation', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Horizontal_Distance_To_Fire_Points'],
      dtype='object')

Filtre os dados em `X` para recuperar somente os índices selecionados. Agora, observe que `indices` é uma tupla contendo um elemento, que é o array com os índices, então nesta construção você deve utilizar `indices[0]` para recuperar os índices dentro da tupla.

In [110]:
indices[0]

array([0, 3, 4, 5, 9])

In [108]:
X_tree = X[:, indices[0]]

In [109]:
X_tree

array([[0.4477459 , 0.15261628, 0.21276596, 0.17181634, 0.31482517],
       [0.42571721, 0.04360465, 0.1929078 , 0.1949177 , 0.35160839],
       [0.2392418 , 0.09229651, 0.21702128, 0.19881606, 0.04741259],
       ...,
       [0.59375   , 0.06540698, 0.20283688, 0.14481663, 0.20839161],
       [0.54559426, 0.2318314 , 0.2141844 , 0.35633843, 0.31888112],
       [0.40420082, 0.11773256, 0.23262411, 0.19766099, 0.23230769]],
      shape=(10000, 5))

Mais uma vez, separe os dados `X_tree` e `y` em split de treinamento, e de teste (com `test_size=0.25`).

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X_tree, 
                                                    y, 
                                                    test_size=0.25, 
                                                    random_state=0)

In [112]:
X_train.shape, X_test.shape

((7500, 5), (2500, 5))

In [113]:
tree_classifier = RandomForestClassifier(random_state=0)
tree_classifier.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [114]:
tree_classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}

Faça predições para os dados de teste, e calcule a acurácia.

In [115]:
y_pred = tree_classifier.predict(X_test) # preditor

In [116]:
accuracy_score(y_test, y_pred)

0.7704

In [117]:
print(f'Acurácia {accuracy_score(y_test, y_pred)*100:.2f} %')

Acurácia 77.04 %


Mais uma vez esta seleção se mostrou pior que utilizar todos os dados, ou seja ficou semelhante a seleção baseada em variância.


Uma das principais diferenças entre os algoritmos Randon Forest e Extra Trees é que o primeiro escolhe uma divisão ideal enquanto o segundo escolhe aleatoriamente.

o algoritmo Random Forest seleciona a melhor divisão para as árvores, enquanto o Extra Trees faz escolhas aleatórias. Isso reflete uma diferença chave entre os dois algoritmos em termos de como eles constroem suas árvores de decisão. 