# 15.6) Salvar um classificador já treinado

In [2]:
import pickle
with open('../11-avaliacao_algoritmos_classificacao/credit_aula_copia.pkl', 'rb') as f:
  X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)   

In [3]:
import numpy as np
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis = 0)

## dados credit => [person_income, person_age, loan_amnt | loan_status]

3 colunas

*** person_income, person_age, loan_amnt

*** renda, idade, e a dívida

income é a renda da pessoa (considerada anualmente)

age

loan_amnt->Loan amount é a dívida que a pessoa possui


---------------------------
Olhar o shape

idade, renda e a dívida => x

somente as classes, paga ou não paga o empréstimo => y


0 (paga)

1 (não paga)

In [4]:
X_credit[:7]

array([[8.000e+04, 2.200e+01, 7.250e+03],
       [6.700e+04, 3.000e+01, 1.000e+04],
       [5.916e+04, 2.500e+01, 1.660e+04],
       [5.800e+04, 2.400e+01, 7.000e+03],
       [4.600e+04, 2.400e+01, 5.975e+03],
       [7.200e+04, 2.600e+01, 5.000e+03],
       [2.000e+05, 2.400e+01, 2.000e+04]])

In [5]:
y_credit[:7]

array([0, 0, 1, 0, 1, 0, 0])

In [6]:
X_credit.shape, y_credit.shape

((32581, 3), (32581,))

## pelo gráfico o melhor algoritmo, pelo 11-5_analise_resultados-ANOVA_Tukey.ipynb, foi o Random_forest e logo o knn, e o terceiro a árvore.

In [7]:
from sklearn.ensemble import RandomForestClassifier # Random Forest
from sklearn.neighbors import KNeighborsClassifier # KNeighbors
from sklearn.tree import DecisionTreeClassifier # árvore de decisão

In [8]:
# pegar os parâmetros selecionados do 11-1_Algoritmos-backup.ipynb

In [9]:
#{'criterion': 'entropy', 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 150}
classificador_random_forest = RandomForestClassifier(criterion= 'entropy', min_samples_leaf = 1, min_samples_split= 10, n_estimators = 150)
classificador_random_forest.fit(X_credit, y_credit)

RandomForestClassifier(criterion='entropy', min_samples_split=10,
                       n_estimators=150)

In [10]:
import pandas as pd
pd.DataFrame(classificador_random_forest.get_params().items(), columns=['Hiperparâmetro', 'Valor'])


,Hiperparâmetro,Valor
0,bootstrap,True
1,ccp_alpha,0.0
2,class_weight,None
3,criterion,entropy
4,max_depth,None
5,max_features,sqrt
6,max_leaf_nodes,None
7,max_samples,None
8,min_impurity_decrease,0.0
9,min_samples_leaf,1


In [11]:
#  {'n_neighbors': 20, 'p': 1}
classificador_knn = KNeighborsClassifier(n_neighbors= 20, p= 1)
classificador_knn.fit(X_credit, y_credit)


KNeighborsClassifier(n_neighbors=20, p=1)

In [12]:
classificador_knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 20,
 'p': 1,
 'weights': 'uniform'}

In [13]:
classificador_knn.get_params().items()

dict_items([('algorithm', 'auto'), ('leaf_size', 30), ('metric', 'minkowski'), ('metric_params', None), ('n_jobs', None), ('n_neighbors', 20), ('p', 1), ('weights', 'uniform')])

In [14]:
# {'criterion': 'entropy', 'min_samples_leaf': 10, 'min_samples_split': 2, 'splitter': 'best'}
classificador_arvore_decisao = DecisionTreeClassifier(criterion= 'entropy', min_samples_leaf=  10, min_samples_split= 2, splitter= 'best')
classificador_arvore_decisao.fit(X_credit, y_credit)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=10)

In [15]:
classificador_arvore_decisao.get_params()


{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 10,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

# salvar nossos dados em um disco

In [16]:
import pickle
pickle.dump(classificador_random_forest, open('random_forest_finalizado.sav', 'wb')) # write para salvar
pickle.dump(classificador_knn, open('knn_finalizado.sav', 'wb'))
pickle.dump(classificador_arvore_decisao, open('arvore_decisao_finalizado.sav', 'wb'))

In [17]:
# para fazer a interface gráfica.

### carregar o modelo

# 15.7)  Carregar um classificador já treinado

In [18]:
random_forest = pickle.load(open('random_forest_finalizado.sav', 'rb')) # read 
knn = pickle.load(open('knn_finalizado.sav', 'rb'))
arvore_decisao = pickle.load(open('arvore_decisao_finalizado.sav', 'rb'))

In [19]:
novo_registro = X_credit[0]
novo_registro

array([8.00e+04, 2.20e+01, 7.25e+03])

In [20]:
novo_registro = X_credit[1999]
novo_registro
#renda, idade, e a dívida

array([2.15e+05, 2.30e+01, 3.50e+04])

In [21]:
novo_registro.shape # 1 dimensão

(3,)

In [22]:
#random_forest.predict(novo_registro)
# antes era formato de vetor, agora é de matriz

#ValueError: Expected 2D array, got 1D array instead:
#array=[2.15e+05 2.30e+01 3.50e+04].
#Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [23]:
# 1 linha e 3 colunas

novo_registro = novo_registro.reshape(1, -1)
novo_registro.shape

(1, 3)

In [24]:
# formato de matriz
novo_registro

array([[2.15e+05, 2.30e+01, 3.50e+04]])

In [25]:
random_forest.predict(novo_registro) # vai pagar a dívida, quando é 0, se fosse 1 não pagaria

array([0])

In [26]:
knn.predict(novo_registro)  # vai pagar a dívida, quando é 0, se fosse 1 não pagaria

array([0])

In [27]:
arvore_decisao.predict(novo_registro)  # vai pagar a dívida, quando é 0, se fosse 1 não pagaria

array([0])

In [28]:
# simular modelo em ambiente de produção

In [29]:
novo_registro = X_credit[0]
print(novo_registro)
novo_registro = novo_registro.reshape(1, -1)
print(novo_registro.shape)
print('registros:',novo_registro)
print('resultado random forest:',random_forest.predict(novo_registro)) # vai pagar a dívida, quando é 0, se fosse 1 não pagaria
print('resultado knn:',knn.predict(novo_registro))
print('resultado árvore:',arvore_decisao.predict(novo_registro))

[8.00e+04 2.20e+01 7.25e+03]
(1, 3)
registros: [[8.00e+04 2.20e+01 7.25e+03]]
resultado random forest: [0]
resultado knn: [0]
resultado árvore: [0]


In [30]:
novo_registro = X_credit[2]
print(novo_registro)
novo_registro = novo_registro.reshape(1, -1)
print(novo_registro.shape)
print('registros:',novo_registro)
print('resultado random forest:',random_forest.predict(novo_registro)) # 1 não pagaria
print('resultado knn:',knn.predict(novo_registro))
print('resultado árvore:',arvore_decisao.predict(novo_registro)) # 1 não pagaria

[5.916e+04 2.500e+01 1.660e+04]
(1, 3)
registros: [[5.916e+04 2.500e+01 1.660e+04]]
resultado random forest: [1]
resultado knn: [0]
resultado árvore: [1]


In [31]:
novo_registro = X_credit[7]
print(novo_registro)
novo_registro = novo_registro.reshape(1, -1)
print(novo_registro.shape)
print('registros:',novo_registro)
print('resultado random forest:',random_forest.predict(novo_registro)) # 0 pagaria
print('resultado knn:',knn.predict(novo_registro))
print('resultado árvore:',arvore_decisao.predict(novo_registro)) # 0 pagaria

[6.24e+04 2.40e+01 1.50e+04]
(1, 3)
registros: [[6.24e+04 2.40e+01 1.50e+04]]
resultado random forest: [0]
resultado knn: [0]
resultado árvore: [0]


In [32]:
novo_registro = X_credit[25]
print(novo_registro)
novo_registro = novo_registro.reshape(1, -1)
print(novo_registro.shape)
print('registros:',novo_registro)
print('resultado random forest:',random_forest.predict(novo_registro)) # 1 não pagaria
print('resultado knn:',knn.predict(novo_registro)) # 1 não pagaria
print('resultado árvore:',arvore_decisao.predict(novo_registro)) # 1 não pagaria

[30000.    33. 11975.]
(1, 3)
registros: [[30000.    33. 11975.]]
resultado random forest: [1]
resultado knn: [1]
resultado árvore: [1]


# 16.3 Combinação de classificadores - implementação 

Previsão para cada um dos algoritmos, e faremos combinações (como se fosse o voto da maioria)


## Combinação de classificadores

In [37]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1, -1)
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

registro [[8.00e+04 2.20e+01 7.25e+03]]
(1, 3)


array([[8.00e+04, 2.20e+01, 7.25e+03]])

In [40]:
resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)

print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria

resultado random forest: 0
resultado knn: 0
resultado árvore: 0


In [42]:
resposta_random_forest

array([0])

In [44]:
# quanto a maior quantidade de votos para o pagaria 0 e n]ao pagaria, será a resposta final do algoritmo. 

paga = 0
nao_paga = 0

if resposta_random_forest[0] == 1:  # igual a 1 não paga, em cada algoritmo.
  nao_paga += 1
else: # igual a 0 paga
  paga += 1

if resposta_knn[0] == 1: # igual a 1 não paga, em cada algoritmo.
  nao_paga += 1
else: # igual a 0 paga
  paga += 1

if resposta_arvore_decisao[0] == 1: # igual a 1 não paga, em cada algoritmo.
  nao_paga += 1
else: # igual a 0 paga
  paga += 1

if paga > nao_paga:
  print('Cliente pagará o empréstimo')
elif paga == nao_paga: # o ideal seria usar o número impar de algoritmos, para evitar o empate. 
    # Ou estabecer pesos em porcentagens para cada algoritmo.
  print('Empate')
else:
  print('Cliente não pagará o empréstimo')

Cliente pagará o empréstimo


In [47]:
# parte 2 teste 

novo_registro = X_credit[25]
novo_registro = novo_registro.reshape(1, -1)
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)

print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria

# quanto a maior quantidade de votos para o pagaria 0 e n]ao pagaria, será a resposta final do algoritmo. 
def resposta_cliente(resposta_random_forest_0, resposta_knn_0, resposta_arvore_decisao_0):
    paga = 0
    nao_paga = 0
    
    if resposta_random_forest_0[0] == 1:  # igual a 1 não paga, em cada algoritmo.
      nao_paga += 1
    else: # igual a 0 paga
      paga += 1
    
    if resposta_knn_0[0] == 1: # igual a 1 não paga, em cada algoritmo.
      nao_paga += 1
    else: # igual a 0 paga
      paga += 1
    
    if resposta_arvore_decisao_0[0] == 1: # igual a 1 não paga, em cada algoritmo.
      nao_paga += 1
    else: # igual a 0 paga
      paga += 1
    
    if paga > nao_paga:
      print('Cliente pagará o empréstimo')
    elif paga == nao_paga: # o ideal seria usar o número impar de algoritmos, para evitar o empate. 
        # Ou estabecer pesos em porcentagens para cada algoritmo.
      print('Empate')
    else:
      print('Cliente não pagará o empréstimo')

resposta_cliente(resposta_random_forest, resposta_knn, resposta_arvore_decisao)        

registro [[30000.    33. 11975.]]
(1, 3)
resultado random forest: 1
resultado knn: 1
resultado árvore: 1
Cliente não pagará o empréstimo


In [49]:
# parte 3 teste 

novo_registro = X_credit[255]
novo_registro = novo_registro.reshape(1, -1)
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)

print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria
resposta_cliente(resposta_random_forest, resposta_knn, resposta_arvore_decisao)        

registro [[1.054e+05 3.100e+01 2.425e+04]]
(1, 3)
resultado random forest: 0
resultado knn: 0
resultado árvore: 1
Cliente pagará o empréstimo


# 16.5) Rejeição de classificadores  implementação

Rejeição de classificadores

Em aplicações reais:

- Aponta uma única hipótese.

- Rejeitar o resultado se não tiver certeza suficiente.


Classifcador para saber a resposta. 

Com as porcentagens, tem que aplicar os critérios de rejeição. Para verificar se vai ser utilizado ou não às respostas; Aceita ou não à resposta;


Problemas com mais de uma hipótese e nenhuma hipótese.


# Rejeição de classificadores

In [52]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1, -1)
print('renda, idade, dívida')
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)
print('se 0 pagaria o empréstimo, se 1 não paga o empréstimo')
print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria

renda, idade, dívida
registro [[8.00e+04 2.20e+01 7.25e+03]]
(1, 3)
se 0 pagaria o empréstimo, se 1 não paga o empréstimo
resultado random forest: 0
resultado knn: 0
resultado árvore: 0


# probabilidade no sklearn



In [55]:
probabilidade_random_forest = random_forest.predict_proba(novo_registro)
probabilidade_random_forest
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.

array([[0.99550265, 0.00449735]])

In [59]:
# Qual é o maior valor da probabilidade?

confianca_random_forest = probabilidade_random_forest.max()
print(confianca_random_forest)

print(f'{confianca_random_forest*100:.2f} % que será 0 (paga)') 

0.9955026455026453
99.55 % que será 0 (paga)


In [60]:
probabilidade_knn = knn.predict_proba(novo_registro)
print(probabilidade_knn)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_knn = probabilidade_knn.max()
print(confianca_knn)

print(f'{confianca_knn*100:.2f} % que será 0 (paga)') 


[[0.95 0.05]]
0.95
95.00 % que será 0 (paga)


In [61]:
probabilidade_arvore_decisao = arvore_decisao.predict_proba(novo_registro)
print(probabilidade_arvore_decisao)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_arvore_decisao = probabilidade_arvore_decisao.max()
print(confianca_arvore_decisao)

print(f'{confianca_arvore_decisao*100:.2f} % que será 0 (paga)') 

[[1. 0.]]
1.0
100.00 % que será 0 (paga)


In [69]:

# quanto a maior quantidade de votos para o pagaria 0 e n]ao pagaria, será a resposta final do algoritmo. 
def resposta_cliente_2(resposta_random_forest_0, confianca_random_forest_0, resposta_knn_0, confianca_knn_0, resposta_arvore_decisao_0, confianca_arvore_decisao_0):
    paga = 0
    nao_paga = 0
    confianca_minima = 0.999999 # confiança precisa ser alta. 
    algoritmos = 0
    
    if confianca_random_forest_0 >= confianca_minima:
      print(f'confiança no algoritmo random forest, de {confianca_random_forest_0*100:.2f}%') 
      algoritmos += 1
      if resposta_random_forest_0[0] == 1:
        nao_paga += 1
      else:
        paga += 1
    
    if confianca_knn_0 >= confianca_minima:
      print(f'confiança no algoritmo  knn, de {confianca_knn_0*100:.2f}%')        
      algoritmos += 1
      if resposta_knn_0[0] == 1:
        nao_paga += 1
      else:
        paga += 1
    
    if confianca_arvore_decisao_0 >= confianca_minima:
      print(f'confiança no algoritmo árvore de decisão, de {confianca_arvore_decisao_0*100:.2f}%.')     
      algoritmos += 1
      if resposta_arvore_decisao_0[0] == 1:
        nao_paga += 1
      else:
        paga += 1
    
    if paga > nao_paga:
      print('Cliente pagará o empréstimo, baseado em {} algoritmos'.format(algoritmos))
    elif paga == nao_paga:
      print('Empate, baseado em {} algoritmos'.format(algoritmos))
    else:
      print('Cliente não pagará o empréstimo, baseado em {} algoritmos'.format(algoritmos))



resposta_cliente_2(resposta_random_forest, confianca_random_forest, resposta_knn, confianca_knn, resposta_arvore_decisao, confianca_arvore_decisao)        

confiança no algoritmo árvore de decisão, de 100.00%.
Cliente pagará o empréstimo, baseado em 1 algoritmos


In [70]:


novo_registro = X_credit[199]
novo_registro = novo_registro.reshape(1, -1)
print('renda, idade, dívida')
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)
print('se 0 pagaria o empréstimo, se 1 não paga o empréstimo')
print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria

# -----------------------------------------------------------------------------------
probabilidade_random_forest = random_forest.predict_proba(novo_registro)
probabilidade_random_forest
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.

# Qual é o maior valor da probabilidade?

confianca_random_forest = probabilidade_random_forest.max()
print(confianca_random_forest)

print(f'{confianca_random_forest*100:.2f} % que será 0 (paga)') 
# -----------------------------------------------------------------------------------

probabilidade_knn = knn.predict_proba(novo_registro)
print(probabilidade_knn)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_knn = probabilidade_knn.max()
print(confianca_knn)

print(f'{confianca_knn*100:.2f} % que será 0 (paga)') 

# -----------------------------------------------------------------------------------

probabilidade_arvore_decisao = arvore_decisao.predict_proba(novo_registro)
print(probabilidade_arvore_decisao)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_arvore_decisao = probabilidade_arvore_decisao.max()
print(confianca_arvore_decisao)

print(f'{confianca_arvore_decisao*100:.2f} % que será 0 (paga)') 


resposta_cliente_2(resposta_random_forest, confianca_random_forest, resposta_knn, confianca_knn, resposta_arvore_decisao, confianca_arvore_decisao)        

renda, idade, dívida
registro [[6.96e+04 4.50e+01 6.00e+03]]
(1, 3)
se 0 pagaria o empréstimo, se 1 não paga o empréstimo
resultado random forest: 0
resultado knn: 0
resultado árvore: 0
0.9342134162134158
93.42 % que será 0 (paga)
[[1. 0.]]
1.0
100.00 % que será 0 (paga)
[[1. 0.]]
1.0
100.00 % que será 0 (paga)
confiança no algoritmo  knn, de 100.00%
confiança no algoritmo árvore de decisão, de 100.00%.
Cliente pagará o empréstimo, baseado em 2 algoritmos


In [75]:


novo_registro = X_credit[33]
novo_registro = novo_registro.reshape(1, -1)
print('renda, idade, dívida')
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)
print('se 0 pagaria o empréstimo, se 1 não paga o empréstimo')
print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria

# -----------------------------------------------------------------------------------
probabilidade_random_forest = random_forest.predict_proba(novo_registro)
probabilidade_random_forest
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.

# Qual é o maior valor da probabilidade?

confianca_random_forest = probabilidade_random_forest.max()
print(confianca_random_forest)

print(f'{confianca_random_forest*100:.2f} % que será 0 (paga)') 
# -----------------------------------------------------------------------------------

probabilidade_knn = knn.predict_proba(novo_registro)
print(probabilidade_knn)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_knn = probabilidade_knn.max()
print(confianca_knn)

print(f'{confianca_knn*100:.2f} % que será 0 (paga)') 

# -----------------------------------------------------------------------------------

probabilidade_arvore_decisao = arvore_decisao.predict_proba(novo_registro)
print(probabilidade_arvore_decisao)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_arvore_decisao = probabilidade_arvore_decisao.max()
print(confianca_arvore_decisao)

print(f'{confianca_arvore_decisao*100:.2f} % que será 0 (paga)') 


resposta_cliente_2(resposta_random_forest, confianca_random_forest, resposta_knn, confianca_knn, resposta_arvore_decisao, confianca_arvore_decisao)        

renda, idade, dívida
registro [[4.0000e+04 2.2000e+01 1.3225e+04]]
(1, 3)
se 0 pagaria o empréstimo, se 1 não paga o empréstimo
resultado random forest: 1
resultado knn: 1
resultado árvore: 1
0.6342921747441873
63.43 % que será 0 (paga)
[[0.4 0.6]]
0.6
60.00 % que será 0 (paga)
[[0.375 0.625]]
0.625
62.50 % que será 0 (paga)
Empate, baseado em 0 algoritmos


In [76]:


novo_registro = X_credit[102]
novo_registro = novo_registro.reshape(1, -1)
print('renda, idade, dívida')
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)
print('se 0 pagaria o empréstimo, se 1 não paga o empréstimo')
print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria

# -----------------------------------------------------------------------------------
probabilidade_random_forest = random_forest.predict_proba(novo_registro)
probabilidade_random_forest
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.

# Qual é o maior valor da probabilidade?

confianca_random_forest = probabilidade_random_forest.max()
print(confianca_random_forest)

print(f'{confianca_random_forest*100:.2f} % que será 0 (paga)') 
# -----------------------------------------------------------------------------------

probabilidade_knn = knn.predict_proba(novo_registro)
print(probabilidade_knn)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_knn = probabilidade_knn.max()
print(confianca_knn)

print(f'{confianca_knn*100:.2f} % que será 0 (paga)') 

# -----------------------------------------------------------------------------------

probabilidade_arvore_decisao = arvore_decisao.predict_proba(novo_registro)
print(probabilidade_arvore_decisao)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_arvore_decisao = probabilidade_arvore_decisao.max()
print(confianca_arvore_decisao)

print(f'{confianca_arvore_decisao*100:.2f} % que será 0 (paga)') 


resposta_cliente_2(resposta_random_forest, confianca_random_forest, resposta_knn, confianca_knn, resposta_arvore_decisao, confianca_arvore_decisao)        

renda, idade, dívida
registro [[8.33e+04 2.60e+01 2.80e+04]]
(1, 3)
se 0 pagaria o empréstimo, se 1 não paga o empréstimo
resultado random forest: 1
resultado knn: 0
resultado árvore: 1
0.7752122469034235
77.52 % que será 0 (paga)
[[0.55 0.45]]
0.55
55.00 % que será 0 (paga)
[[0.375 0.625]]
0.625
62.50 % que será 0 (paga)
Empate, baseado em 0 algoritmos


In [77]:


novo_registro = X_credit[22]
novo_registro = novo_registro.reshape(1, -1)
print('renda, idade, dívida')
print(f'registro {novo_registro}')
print(f'{novo_registro.shape}')
novo_registro

resposta_random_forest= random_forest.predict(novo_registro)
resposta_knn = knn.predict(novo_registro)
resposta_arvore_decisao = arvore_decisao.predict(novo_registro)
print('se 0 pagaria o empréstimo, se 1 não paga o empréstimo')
print('resultado random forest:',resposta_random_forest[0]) #  0 pagaria o empréstimo
print('resultado knn:',resposta_knn[0]) # 0 pagaria
print('resultado árvore:',resposta_arvore_decisao[0]) # 0 pagaria

# -----------------------------------------------------------------------------------
probabilidade_random_forest = random_forest.predict_proba(novo_registro)
probabilidade_random_forest
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.

# Qual é o maior valor da probabilidade?

confianca_random_forest = probabilidade_random_forest.max()
print(confianca_random_forest)

print(f'{confianca_random_forest*100:.2f} % que será 0 (paga)') 
# -----------------------------------------------------------------------------------

probabilidade_knn = knn.predict_proba(novo_registro)
print(probabilidade_knn)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_knn = probabilidade_knn.max()
print(confianca_knn)

print(f'{confianca_knn*100:.2f} % que será 0 (paga)') 

# -----------------------------------------------------------------------------------

probabilidade_arvore_decisao = arvore_decisao.predict_proba(novo_registro)
print(probabilidade_arvore_decisao)
# probabilidade para a classe 0, probabilidade da classe 1, há apenas duas (2) classes.
# Qual é o maior valor da probabilidade?

confianca_arvore_decisao = probabilidade_arvore_decisao.max()
print(confianca_arvore_decisao)

print(f'{confianca_arvore_decisao*100:.2f} % que será 0 (paga)') 


resposta_cliente_2(resposta_random_forest, confianca_random_forest, resposta_knn, confianca_knn, resposta_arvore_decisao, confianca_arvore_decisao)        

renda, idade, dívida
registro [[4800.   24. 2400.]]
(1, 3)
se 0 pagaria o empréstimo, se 1 não paga o empréstimo
resultado random forest: 1
resultado knn: 1
resultado árvore: 1
0.9379747012247008
93.80 % que será 0 (paga)
[[0.05 0.95]]
0.95
95.00 % que será 0 (paga)
[[0. 1.]]
1.0
100.00 % que será 0 (paga)
confiança no algoritmo árvore de decisão, de 100.00%.
Cliente não pagará o empréstimo, baseado em 1 algoritmos
