# Combinação e rejeição de classificadores

## 16.7) Solução o exercício de combinação e Rejeição de classificadores

In [1]:
# Importação das bibliotecas
import pickle
import numpy as np

## Combinação de classificadores

Mais uma vez, vamos começar carregando os dados de treino e teste a partir do arquivo `cover_types.pkl`.

In [6]:
# salvo no git Machine_Learning/Machine_Learning_AZ/9-avaliacao_algoritmos_classificacao/salvos/
import os

DRIVE_DIRECTORY1 = "../11-avaliacao_algoritmos_classificacao/"

with open(os.path.join(DRIVE_DIRECTORY1, "cover_type.pkl"), "rb") as f:
    (X_train, y_train, X_test, y_test) = pickle.load(f)

In [7]:
X_train[20]

array([-0.34764783,  0.79186021,  1.05145865, -0.7695831 , -0.38858928,
        1.81140473, -1.59603158,  1.39775838,  1.84638158, -1.12627519,
        1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ])

Também carregue os classificadores salvos no último exercício.

In [10]:
# no git Machine_Learning/Machine_Learning_AZ/9-avaliacao_algoritmos_classificacao/respostasexercicio_pasta_salvar_testes/
DRIVE_DIRECTORY =  "../11-avaliacao_algoritmos_classificacao/pasta_salvar_testes"

tree = pickle.load(open(os.path.join(DRIVE_DIRECTORY, "tree.sav"), 'rb'))
rf = pickle.load(open(os.path.join(DRIVE_DIRECTORY, "rf.sav"), 'rb'))
knn = pickle.load(open(os.path.join(DRIVE_DIRECTORY, "knn.sav"), 'rb'))
lr = pickle.load(open(os.path.join(DRIVE_DIRECTORY, "lr.sav"), 'rb'))
svm = pickle.load(open(os.path.join(DRIVE_DIRECTORY, "svm.sav"), 'rb'))
neural_net = pickle.load(open(os.path.join(DRIVE_DIRECTORY, "neural_net.sav"), 'rb'))

/home/fabiene/anaconda3/envs/Udemy/lib/python3.11/site-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.4.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/fabiene/anaconda3/envs/Udemy/lib/python3.11/site-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.4.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/fabiene/anaconda3/envs/Udemy/lib/python3.11/site-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator KNeighbo

Separe o registro de índice 2 de `X_test` em uma variável `new_instance`, aplicando o método `reshape` para que o array resultante seja representado em `1` linha e o número de colunas igual ao número de atributos (você pode usar `-1` para o NumPy determinar este número sozinho). Exiba `new_instance` e seu `shape`.

In [11]:
# 1 linha e 53 colunas

In [13]:
new_instance = X_test[2].reshape(1, -1)
new_instance, new_instance.shape # precisamos desses formatos para enviar os dados aos nossos algoritmos 

(array([[-2.42751612, -0.35810696,  2.39062347, -0.83105729,  0.0410722 ,
         -1.2884323 ,  1.55697188, -1.6248467 , -2.70414875, -0.11760965,
          0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ]]),
 (1, 53))

Agora utilize `new_instance` para obter predições dos algoritmos carregados.

In [14]:
# previsão

y_pred_tree = tree.predict(new_instance)
y_pred_rf = rf.predict(new_instance)
y_pred_knn = knn.predict(new_instance)
y_pred_lr = lr.predict(new_instance)
y_pred_svm = svm.predict(new_instance)
y_pred_nn = neural_net.predict(new_instance)

In [26]:
import pandas as pd
set(pd.Series(y_test).unique())

{0, 1, 2, 3, 4, 5, 6}

In [27]:
y_pred_tree

array([1])

Exiba os resultados da predições.

In [28]:
y_pred_tree[0], y_pred_rf[0], y_pred_knn[0], y_pred_lr[0], y_pred_svm[0], y_pred_nn[0]

(1, 1, 1, 5, 5, 1)

In [33]:
print(f"""previsão tree árvore de decisão:{y_pred_tree[0]},
previsão rf random forecast:{y_pred_rf[0]},
previsão  knn :{y_pred_knn[0]},
previsão  lr regressão logistica:{y_pred_lr[0]},
previsão  svm :{y_pred_svm[0]},
previsão  rede neural :{y_pred_nn[0]},
""")

# mais de uma classe, para determinar a classe vencerorar, temos que colocar em uma lista

previsão tree árvore de decisão:1,
previsão rf random forecast:1,
previsão  knn :1,
previsão  lr regressão logistica:5,
previsão  svm :5,
previsão  rede neural :1,



Como este é um problema com mais de uma classe, a lógica para determinar a classe vencedora é um pouco diferente. Vamos começar colocando os resultados em uma lista.

In [34]:
results = [y_pred_tree[0], y_pred_rf[0], y_pred_knn[0], y_pred_lr[0], y_pred_svm[0], y_pred_nn[0]]

In [35]:
results

[1, 1, 1, 5, 5, 1]

Agora, utilizando a função `np.unique`, vamos determinar quais são as classes preditas e quantas vezes elas foram preditas.

In [36]:
unique, counts = np.unique(results, return_counts=True)
unique, counts

(array([1, 5]), array([4, 2]))

In [39]:
print(f'únicas classes:    {unique}') 
print(f'contagens classes: {counts}')
# classe 1 prevista 4 vezes e 5 foram 2 vezes.

únicas classes:    [1 5]
contagens classes: [4 2]


Agora é preciso verificar qual a classe que apareceu mais vezes. Primeiro vamos determinar qual a contagem máxima.

In [40]:
max_counts = counts.max()
max_counts

4

E agora nós conseguimos filtrar as classes que mais apareceram como sendo aquelas cuja contagem é igual á contagem máxima.

In [41]:
top_classes = unique[counts == max_counts]
top_classes

array([1])

Finalmente, a lógica vai utilizar `top_classes` para exibir os resultados.

In [43]:
if len(top_classes) == 1:
    print("Classe encontrada:", top_classes[0])
else:
    print("Empate entre as classes:", top_classes)

Classe encontrada: 1


## Rejeição de classificadores

Utilize o método `predict_proba` para determinar as probabilidades encontradas pelos classificadores. Entretanto, você precisa deixar o algoritmo SVM de fora, porque da forma que nós o implementamos, ele não retorna valores de probabilidade.


In [44]:
y_prob_tree = tree.predict_proba(new_instance)
y_prob_rf = rf.predict_proba(new_instance)
y_prob_knn = knn.predict_proba(new_instance)
y_prob_lr = lr.predict_proba(new_instance)
y_prob_nn = neural_net.predict_proba(new_instance)
# porcentagem de pertencer as classes, com 7 classes.
y_prob_tree, y_prob_rf, y_prob_knn, y_prob_lr, y_prob_nn

(array([[0., 1., 0., 0., 0., 0., 0.]]),
 array([[0.01, 0.79, 0.  , 0.  , 0.  , 0.2 , 0.  ]]),
 array([[0.        , 0.66666667, 0.        , 0.        , 0.        ,
         0.33333333, 0.        ]]),
 array([[2.47850469e-04, 4.34452688e-01, 3.00123084e-02, 6.02930965e-11,
         5.07713265e-03, 5.30200203e-01, 9.81770988e-06]]),
 array([[6.08322093e-10, 8.65393795e-01, 6.26721378e-03, 1.06256638e-20,
         5.86390930e-05, 1.28280351e-01, 2.48434663e-10]]))

Determine a confiança dos classificadores, sendo igual à probabilidade máxima atribuída.

In [46]:
# maior prbabilidade atribuída
confidence_tree = y_prob_tree.max()
confidence_rf = y_prob_rf.max()
confidence_knn = y_prob_knn.max()
confidence_lr = y_prob_lr.max()
confidence_nn = y_prob_nn.max()

confidence_tree, confidence_rf, confidence_knn, confidence_lr, confidence_nn

(1.0, 0.79, 0.6666666666666666, 0.5302002028216072, 0.8653937949402792)

A lógica em si é parecida com a do problema binário, mas primeiro nós filtramos para manter somente os resultados maiores que a confiança mínima. Depois, aplicamos o mesmo código mostrado na combinação de classificadores.

Utilize uma confiança mínima um pouco mais baixa, já que os resultados encontrados acima são menores. Isso é comum em problemas de classificação com mais de duas classes.

In [56]:
# limite mínimo de confiança
min_confidence = 0.75
n_algorithms = 0
results = []

if confidence_tree >= min_confidence:
    n_algorithms += 1
    print(f'Tree: entrou na confiabilidade {confidence_tree*100:.2f} %') 
    print(f'Tree, classe: {y_pred_tree[0]}')  
    results.append(y_pred_tree[0])

if confidence_rf >= min_confidence:
    print(f'Randon forest: entrou na confiabilidade {confidence_rf*100:.2f} %') 
    print(f'Randon forest:  {y_pred_rf[0]}')  
    n_algorithms += 1
    results.append(y_pred_rf[0])

if confidence_knn >= min_confidence:
    print(f'knn: entrou na confiabilidade {confidence_knn*100:.2f} %') 
    print(f'knn:  {y_pred_knn[0]}')        
    n_algorithms += 1
    results.append(y_pred_knn[0])

if confidence_lr >= min_confidence:
    print(f'lr Regressão logistica: entrou na confiabilidade {confidence_lr*100:.2f} %') 
    print(f'lr:  {y_pred_lr[0]}')     
    n_algorithms += 1
    results.append(y_pred_lr[0])

if confidence_nn >= min_confidence:
    print(f'redes neurais: entrou na confiabilidade {confidence_nn*100:.2f} %') 
    print(f'redes neurais:  {y_pred_nn[0]}')          
    n_algorithms += 1
    results.append(y_pred_nn[0])

unique, counts = np.unique(results, return_counts=True) # contagem das classes 
max_counts = counts.max() # máxima contagem
top_classes = unique[counts == max_counts] # qual teve o maior valor

if len(top_classes) == 1:
    print(f"Classe encontrada: {top_classes[0]}, baseado em {n_algorithms} algoritmos.")
else:
    print(f"Empate entre as classes: {top_classes}, baseado em {n_algorithms} algoritmos.")

Tree: entrou na confiabilidade 100.00 %
Tree, classe: 1
Randon forest: entrou na confiabilidade 79.00 %
Randon forest:  1
redes neurais: entrou na confiabilidade 86.54 %
redes neurais:  1
Classe encontrada: 1, baseado em 3 algoritmos.


In [55]:
results

[1, 1, 1]